### ISSUE TITLE
Hyperparameters and arguments

### ISSUE THREAD

**Issue by ajbrock** [lancopku/LabelEmb#1]
Hi guys,

In the paper, you state that you leave alpha at 0.9 for all tasks, but in the code for CIFAR the default value appears to be 0.5. Further, the README says to use mode=='emb', but the comp_loss function can either return losses corresponding to mode='baseline', mode='emb' or mode is neither, and it looks like the code on e.g. line 109 of ResNet18 is where you actually calculate the loss used in your paper (equation 14). Line 101, which is what mode='emb' returns, looks to be missing several terms. Clarification regarding this would be appreciated.

**Comment by imwebson** [comment]
@ajbrock  “alpha" in the codes is not the same variable as in the paper, i am sorry for the confusion and i have fix it according to the paper.   Before committing the codes i did some other small experiments and i forgot to remove them, which caused the second problem.  It should be ok now~ Thank you!
